### ISSUE TITLE
SyntaxError: Unexpected token ﻿ in JSON at position 0

### ISSUE THREAD

**Issue by Valera1980** [jwbay/i18next-json-sync#15]
I try run next command
node src/scripts/syncTranslateResources.js
where 
scrypt is:
`const sync = require('i18next-json-sync').default;
try{

  sync({
    /** Audit files in memory instead of changing them on the filesystem and
      * throw an error if any changes would be made */
    check: false,
    /** Glob pattern for the resource JSON files */
    files: 'src/assets/lang/*.json',
    /** Primary localization language. Other language files will be changed to match */
    primary: 'uk',
    /** Language files to create if they don't exist, e.g. ['es, 'pt-BR', 'fr'] */
    createResources: [],
    /** Space value used for JSON.stringify when writing JSON files to disk */
    space: 4,
    /** Line endings used when writing JSON files to disk. Either LF or CRLF */
    lineEndings: 'LF',
    /** Insert a final newline when writing JSON files to disk */
    finalNewline: false,
    /** Use empty string for new keys instead of the primary language value */
    newKeysEmpty: false
  })

}catch(e){
  console.log(e);
}`
and every time get error:

`
SyntaxError: Unexpected token ﻿ in JSON at position 0
    at JSON.parse (<anonymous>)
    at C:\Proj\AdSaver\LmsAdSaver\node_modules\i18next-json-sync\dist\LocalizationFolder.js:19:38
    at Array.map (<anonymous>)
    at LocalizationFolder.populateFromDisk (C:\Proj\AdSaver\LmsAdSaver\node_modules\i18next-json-sync\dist\LocalizationFolder.js:17:57)
    at sync (C:\Proj\AdSaver\LmsAdSaver\node_modules\i18next-json-sync\dist\index.js:20:16)
    at Object.<anonymous> (C:\Proj\AdSaver\LmsAdSaver\src\scripts\syncTranslateResources.js:4:3)
    at Module._compile (internal/modules/cjs/loader.js:689:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:700:10)
    at Module.load (internal/modules/cjs/loader.js:599:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:538:12)`

**Comment by jwbay** [comment]
This error is coming from Node's built-in JSON parsing, so there's nothing this library can do for that. It's likely the first character in your JSON file is an invalid meta-character like a UTF8 BOM.

**Comment by Valera1980** [comment]
Is it possible add some check condition for before Json.parse()?
